### ISSUE TITLE
needs more NuGet

### ISSUE THREAD

**Issue by MrMitch** [chteuchteu/MaterialDesignIcons-CSharp-Consts#1]
Put it into a ~~chicken~~ [NuGet package](https://docs.nuget.org/create/creating-and-publishing-a-package).

![404 NuGet not found](http://66.media.tumblr.com/e386a4debf9c8125d86a2187eb44a21a/tumblr_milqmbb6wF1qzlbu0o1_500.gif)

**Comment by quentin-st** [comment]
[![Goddamn right](https://media.giphy.com/media/U1XhGr8CWqvVC/giphy.gif)](https://www.nuget.org/packages/MaterialDesignIcons-CSharp-Consts/1.0.0)
